import assert from 'node:assert/strict';
import fs from 'node:fs';
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.CPP_PLAYWRIGHT_PACKAGE || 'playwright');
const base = process.env.CPP_PREVIEW_URL || 'http://127.0.0.1:4175/cp-payroll-quote-calculator/';
const key = 'cpp-quote-builder:studio:quotes:v2';
const originalKey = 'cpp-quote-builder:quotes';
const earlierKey = 'cpp-quote-builder:codex-preview:quotes:v1';
const output = 'tmp/studio-qa';
fs.mkdirSync(output, { recursive: true });
const browser = await chromium.launch({ channel: process.env.CPP_BROWSER || 'msedge', headless: true });
const context = await browser.newContext({ viewport: { width: 1440, height: 1050 } });
const page = await context.newPage();
const errors = [];
page.on('pageerror', error => errors.push(error.message));
const checks = [];
const screenshot = name => page.screenshot({ path: output + '/' + name + '.png', fullPage: true });
const nav = name => page.getByRole('navigation', { name: 'Workspace navigation' }).getByRole('button', { name, exact: true }).click();
const close = () => page.getByRole('button', { name: 'Close panel', exact: true }).click();
const amount = expected => page.waitForFunction(value => document.querySelector('.qs-tray-price>strong')?.textContent === value, expected);
const edit = name => page.getByRole('button', { name: 'Details and pricing for ' + name, exact: true }).click();
const openSummary = async text => { const locator = page.locator('dialog summary').filter({ hasText: text }); if (!(await locator.evaluate(el => el.parentElement.open))) await locator.click(); };
const save = async name => {
  await page.getByRole('button', { name: 'Save draft', exact: true }).click();
  await page.getByLabel('Quote name', { exact: true }).fill(name);
  await page.getByRole('button', { name: 'Save quote', exact: true }).click();
};

try {
  await page.goto(base);
  await page.evaluate(() => document.fonts.ready);
  await amount('$88.50');
  await page.evaluate(({ originalKey, earlierKey }) => {
    localStorage.setItem(originalKey, JSON.stringify({ original: 'protected' }));
    localStorage.setItem(earlierKey, JSON.stringify({ earlier: 'protected' }));
  }, { originalKey, earlierKey });
  await page.getByLabel('Client / company', { exact: true }).fill('Northstar Studio');
  await save('Baseline');
  const baseline = await page.evaluate(k => JSON.parse(localStorage.getItem(k)).Baseline, key);
  await screenshot('build');
  await page.getByLabel('Active employees', { exact: true }).fill('25');
  for (const name of ['TLM (Timekeeping)', 'HCM Core', 'ACA Reporting']) await page.getByRole('button', { name: 'Add ' + name, exact: true }).click();
  await amount('$265.50');
  await page.getByRole('button', { name: 'Undo', exact: true }).click();
  await amount('$250.50');
  await page.getByRole('button', { name: 'Add ACA Reporting', exact: true }).click();
  await page.getByRole('button', { name: 'Add a discount or adjust annual fees' }).click();
  await page.getByLabel('Discount (%)', { exact: true }).fill('10');
  await close();
  await amount('$238.95');
  await page.getByLabel('Pay frequency', { exact: true }).selectOption('monthly');
  await amount('$238.95');
  await page.getByLabel('Pay frequency', { exact: true }).selectOption('biweekly');
  await page.getByLabel('Search all services').fill('expense');
  await page.getByRole('button', { name: 'Add Expense Tracking', exact: true }).click();
  await edit('Expense Tracking');
  await page.getByLabel('Expense tracking users', { exact: true }).fill('12');
  await close();
  await amount('$253.90');
  await page.getByLabel('Search all services').fill('401');
  await page.getByRole('button', { name: /Add 360/ }).click();
  await page.getByRole('button', { name: /Details and pricing for 360/ }).click();
  await openSummary('Rate & discount');
  await page.getByLabel('Do not apply recurring discount', { exact: true }).check();
  await page.getByLabel('Rate per employee ($)', { exact: true }).fill('1');
  await page.getByLabel('Minimum per payroll ($)', { exact: true }).fill('20');
  await screenshot('service-inspector');
  await page.keyboard.press('Escape');
  assert.equal(await page.getByRole('dialog').count(), 0);
  await amount('$278.90');
  await page.getByRole('button', { name: 'Client details', exact: false }).first().click();
  await page.getByLabel('Approximate W-2s', { exact: true }).fill('40');
  await page.getByLabel('Approximate 1099s', { exact: true }).fill('5');
  await page.getByLabel('Include my contact information').check();
  await page.getByLabel('Representative name', { exact: true }).fill('Alex Morgan');
  await page.getByLabel('Phone number', { exact: true }).fill('555-010-0123');
  // Modal keyboard focus cannot escape into the underlying catalog.
  for (let i = 0; i < 24; i++) await page.keyboard.press('Tab');
  assert.equal(await page.evaluate(() => !!document.activeElement.closest('dialog')), true);
  await close();
  await amount('$330.35');
  await page.getByRole('button', { name: '10% recurring discount' }).click();
  await page.getByLabel('Annual forms count override').fill('60');
  await page.getByLabel('W-2 / 1099 rate per form ($)', { exact: true }).fill('8.25');
  await close();
  await page.getByLabel('Search all services').fill('payroll processing');
  await edit('Payroll Processing');
  await openSummary('Rate & discount');
  await page.getByLabel('Override payroll base rate', { exact: true }).check();
  await page.getByLabel('Base rate per payroll ($)', { exact: true }).fill('150');
  await close();
  await amount('$422.15');
  await save('Adjusted');
  const adjusted = await page.evaluate(k => JSON.parse(localStorage.getItem(k)).Adjusted, key);
  await page.reload();
  await nav('Saved quotes');
  await page.locator('.qs-draft-library tr').filter({ hasText: 'Adjusted' }).getByRole('button', { name: 'Open', exact: false }).click();
  await amount('$422.15');
  await nav('Saved quotes');
  await screenshot('saved-quotes');
  assert.equal(await page.evaluate(k => JSON.parse(localStorage.getItem(k)).original, originalKey), 'protected');
  assert.equal(await page.evaluate(k => JSON.parse(localStorage.getItem(k)).earlier, earlierKey), 'protected');
  checks.push('Flat-frequency pricing, user/W-2/1099 counts, discounts and exclusion, setup/rate controls, selection undo, save/load and both storage boundaries');

  const seeded = async (snapshot, classic = false) => {
    await page.goto(base + (classic ? '?experience=classic' : ''));
    await page.evaluate(({ k, snapshot }) => localStorage.setItem(k, JSON.stringify({ Sample: snapshot })), { k: classic ? originalKey : key, snapshot });
    await page.reload();
    if (classic) await page.getByRole('button', { name: 'Load', exact: true }).click();
    else { await nav('Saved quotes'); await page.getByRole('button', { name: 'Open', exact: false }).click(); await nav('Document preview'); }
    await page.evaluate(() => document.fonts.ready);
  };
  const all = structuredClone(baseline);
  all.selectedModules = Object.fromEntries(Object.keys(all.selectedModules).map(k => [k, true]));
  all.selectedAncillary = Object.fromEntries(Object.keys(all.selectedAncillary).map(k => [k, true]));
  all.benefitEdi = { enabled: true, feeds: 2, cobraBundle: true };
  all.stateTaxId = { enabled: true, quantity: 2 };
  all.pytd = { enabled: true, hours: 2.5, statements: 500 };
  all.discountPercent = 5;
  all.discountOptOut = { retirement: true };
  all.showRepInfo = true;
  all.repName = 'Alex Morgan';
  all.repPhone = '555-010-0123';
  const scorp = { ...baseline, sCorpMode: true, employeeCount: 1, frequency: 'annual' };
  const mixed = { ...scorp, frequency: 'monthly', benefitEdi: { enabled: true, feeds: 1, cobraBundle: false } };
  for (const [name, snapshot] of Object.entries({ simple: baseline, adjusted, 'all-services': all, scorp, mixed })) {
    await seeded(snapshot);
    const newText = await page.locator('.qs-documents').innerText();
    await page.pdf({ path: output + '/' + name + '.pdf', printBackground: true, preferCSSPageSize: true, displayHeaderFooter: false });
    if (name === 'simple') await screenshot('document');
    if (name === 'mixed') { assert.match(newText, /Separate billing schedules/); assert.match(newText, /\$250.00 \/quarter/); assert.match(newText, /\$40.00 \/payroll/); }
    await seeded(snapshot, true);
    const classicText = (await page.locator('.print-container').allInnerTexts()).join('\n');
    assert.equal(newText.replace(/\s+/g, ' ').trim(), classicText.replace(/\s+/g, ' ').trim(), 'Document parity: ' + name);
    checks.push('Pricing and document text parity, with print sample: ' + name);
  }
  await seeded(scorp);
  await nav('Build quote');
  await page.getByRole('button', { name: 'Client details', exact: false }).first().click();
  await page.getByLabel('Owner-only S-Corp payroll').uncheck();
  await close();
  await page.getByLabel('Active employees', { exact: true }).fill('27');
  await page.getByRole('button', { name: 'Client details', exact: false }).first().click();
  await page.getByLabel('Owner-only S-Corp payroll').check();
  await close();
  await amount('$250.00');
  await page.getByLabel('Pay frequency', { exact: true }).selectOption('annual');
  await amount('$1,000.00');
  assert.equal(await page.locator('.qs-card').count(), 1);
  await nav('Document preview');
  await page.getByRole('button', { name: 'Edit client details', exact: false }).click();
  await page.getByLabel('Owner-only S-Corp payroll').uncheck();
  await close();
  await nav('Build quote');
  assert.equal(await page.getByLabel('Active employees', { exact: true }).inputValue(), '27');
  checks.push('S-Corp entry/exit, preserved standard settings, annual schedule and separate mixed-schedule display');
  await seeded(baseline);
  await page.getByRole('button', { name: 'Internal sales', exact: true }).click();
  assert.match(await page.locator('.qs-documents').innerText(), /ANNUAL EST/i);
  await page.getByRole('button', { name: 'Client proposal', exact: true }).click();
  assert.equal(await page.locator('.qs-documents>section').count(), 3);
  for (const width of [1280, 1440, 1920]) {
    await page.setViewportSize({ width, height: 1000 });
    await nav('Build quote');
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, 'Viewport overflow ' + width);
    await nav('Document preview');
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, 'Document overflow ' + width);
  }
  await nav('Build quote');
  await page.keyboard.press('Control+k');
  assert.equal(await page.getByLabel('Search all services').evaluate(el => el === document.activeElement), true);
  await page.emulateMedia({ media: 'print' });
  assert.equal(await page.locator('.qs-sidebar').isVisible(), false);
  assert.equal(await page.locator('.qs-documents').isVisible(), true);
  checks.push('Client/internal output, keyboard search, modal focus/escape, three laptop sizes, print visibility');
  assert.deepEqual(errors, []);
  fs.writeFileSync(output + '/report.json', JSON.stringify({ passed: checks, browserErrors: errors }, null, 2));
  console.log(JSON.stringify({ passed: checks, browserErrors: errors }, null, 2));
} finally { await browser.close(); }
